name: PR Build Check

on:
  pull_request:
    branches:
      - main
      - release

jobs:
  build:
    name: PR Yarn Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update apt
        run: sudo apt update

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      
      - name: Setup Yarn
        run: npm install -g yarn
  
      - name: Install Dependencies
        run: yarn install